import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
            <li><Link href="/read/3">js</Link></li>
        </ol>
        {children}
        <ul>
            <li>
                <Link href="/create">생성</Link>
            </li>
            <li>
                <Link href="/update/1">Update</Link>
            </li>
            <li>
                <button>delete</button>
            </li>
        </ul>
      </body>
    </html>
  );
}
